import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import image1 from "../../public/images/1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Prueba</h1>
      <Image
        src={image1}
        alt="Vercel Logo"
        // width={100}
        // height={24}
        priority
      />
    </>
  );
}
